name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Run the checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile=minimal --component=clippy --component=rustfmt
      - run: cargo clippy -- -D warnings
      - run: cargo fmt --all -- --check

  bench:
    name: Run the benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install nightly --profile=minimal
      - run: cargo +nightly bench

  test:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable --profile=minimal
      - run: cargo test
